import { formatDate } from '@/lib/date'

interface PtmLogLike {
  id: string
  studentId: string
  studentName: string
  rollNo: string
  batch: string
  date: string
  parentName?: string
  parentAttended: boolean
  discussionNotes: string
  actionItems: string
  followUpDate?: string
}

function safeFileTag(title: string): string {
  return (title || 'Report').replace(/[^a-z0-9]+/gi, '_').slice(0, 60)
}

type RGB = [number, number, number]
const ink: RGB = [17, 24, 39]
const muted: RGB = [90, 90, 90]
const accent: RGB = [79, 70, 229]

export async function buildPtmReportPDF(log: PtmLogLike): Promise<{ doc: any; filename: string }> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 18
  const contentWidth = pageWidth - margin * 2

  let y = 20

  // Header
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.setTextColor(...ink)
  doc.text('Parent-Teacher Meeting Report', pageWidth / 2, y, { align: 'center' })
  y += 9

  // Date and Batch row
  doc.setFontSize(9)
  const col2 = margin + 80

  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...ink)
  doc.text('Date of Meeting', margin, y)
  doc.text('Batch / Class', col2, y)
  y += 5
  
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...muted)
  doc.text(formatDate(log.date), margin, y)
  doc.text(log.batch || '—', col2, y)
  y += 8

  // Student details row
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...ink)
  doc.text('Student Name', margin, y)
  doc.text('Roll Number', col2, y)
  y += 5

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...muted)
  doc.text(log.studentName || '—', margin, y)
  doc.text(log.rollNo || '—', col2, y)
  y += 8

  // Parent details row
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...ink)
  doc.text('Parent Name', margin, y)
  doc.text('Parent Attended', col2, y)
  y += 5

  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...muted)
  doc.text(log.parentName || '—', margin, y)
  
  if (log.parentAttended) {
    doc.setTextColor(5, 150, 105) // emerald
    doc.setFont('helvetica', 'bold')
    doc.text('Yes', col2, y)
  } else {
    doc.setTextColor(225, 29, 72) // rose
    doc.setFont('helvetica', 'bold')
    doc.text('No', col2, y)
  }
  y += 8

  // Divider
  doc.setDrawColor(...accent)
  doc.setLineWidth(0.8)
  doc.line(margin, y, pageWidth - margin, y)
  y += 8

  // Discussion Notes
  const addSection = (title: string, content: string, isActionItems = false) => {
    if (y + 15 > pageHeight - 20) {
      doc.addPage()
      y = 20
    }
    
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(10)
    doc.setTextColor(isActionItems ? 79 : 17, isActionItems ? 70 : 24, isActionItems ? 229 : 39) // Accent for action items
    doc.text(title, margin, y)
    y += 6

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9.5)
    doc.setTextColor(...ink)
    
    const text = content || '—'
    const wrapped = doc.splitTextToSize(text, contentWidth)
    
    if (y + wrapped.length * 5 > pageHeight - 20) {
      doc.addPage()
      y = 20
    }
    
    doc.text(wrapped, margin, y)
    y += wrapped.length * 5 + 6
  }

  addSection('Discussion Notes', log.discussionNotes)
  
  if (log.actionItems) {
    addSection('Action Items & Commitments', log.actionItems, true)
  }

  if (log.followUpDate) {
    if (y + 10 > pageHeight - 20) {
      doc.addPage()
      y = 20
    }
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(...ink)
    doc.text('Follow-up Scheduled For:', margin, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...accent)
    doc.text(formatDate(log.followUpDate), margin + 45, y)
    y += 8
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setDrawColor(200, 200, 200)
    doc.setLineWidth(0.3)
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15)
    
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(8)
    doc.setTextColor(...muted)
    doc.text('Generated by Academic Planning System', margin, pageHeight - 10)
    
    doc.setFont('helvetica', 'normal')
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' })
  }

  return { doc, filename: `PTM_Report_${safeFileTag(log.studentName)}_${log.date}.pdf` }
}

export async function downloadPtmReportPDF(log: PtmLogLike) {
  const { doc, filename } = await buildPtmReportPDF(log)
  doc.save(filename)
}
